# Configuration file for unit test runner at http://travis-ci.org/#!/drush-ops/drush
language: php
php:
  - 5.3
env:
  - UNISH_DB_URL=mysql://root:@127.0.0.1 
before_script:
  - cd ..; git clone git://github.com/drush-ops/drush.git; cd drush_entity
  - export UNISH_DRUSH="${PWD}/../drush/drush" 
  - export PHPUNIT_ARGS=--bootstrap="${PWD}/../drush/tests/drush_testcase.inc"
  - cd tests
  - env
script: phpunit --debug $PHPUNIT_ARGS

